server:
  port: 8882
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
spring:
  redis:
    host: 140.143.197.165
    password: Qin74654...
    port: 6379
  application:
    name: zuul
  datasource:
    name: test
    url: jdbc:mysql://192.168.1.117:3306/itmayiedu-member?characterEncoding=UTF-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  #routes:
  #  api-feign:
  #    strip-prefix: true
  #    path: /feign/**
  #    service-id: feign
  ratelimit:
    key-prefix: feign  #对应用来标识请求的key的前缀
    enabled: true
    repository: redis  #对应存储类型（用来存储统计信息）
    behind-proxy: true  #代理之后
    default-policy: #可选 - 针对所有的路由配置的策略，除非特别配置了policies
      limit: 10 #可选 - 每个刷新时间窗口对应的请求数量限制
      quota: 1000 #可选-  每个刷新时间窗口对应的请求时间限制（秒）
      refresh-interval: 60 # 刷新时间窗口的时间，默认值 (秒)
      type: #可选 限流方式
        - user
        - origin
        - url
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
